### ISSUE TITLE
deprecated function

### ISSUE THREAD

**Issue by thorade** [UdK-VPT/CoTeTo#8]
https://github.com/UdK-VPT/CoTeTo/blob/c0d59c72ad9cb2513db173d441644adec3da1e19/CoTeTo/import_file.py#L12

PyCharm tells me to use `importlib.util.find_spec()` instead!?

https://docs.python.org/3/library/importlib.html#importlib.find_loader
https://docs.python.org/3/library/importlib.html#importlib.util.find_spec

**Comment by jraedler** [comment]
The method loader.load_module() is deprecated as well, the new recommended way is shown in this example:

https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

But it looks like this code does not work with zip.zipimporter, since exec_module() is not implemented there. Switching to this code now would disable using generators contained in zip files. So I would recommend to keep the deprecated code (as long as it still works) until the new method is completely implemented.

**Comment by thorade** [comment]
Yes, it will probably work for a couple of years.
